/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    UtcTimeResponse,
    UtcTimeResponseFromJSON,
    UtcTimeResponseToJSON,
} from '../models';

/**
 * 
 */
export class TimeSyncApi extends runtime.BaseAPI {

    /**
     * Gets the current utc time.
     */
    async getUtcTimeRaw(): Promise<runtime.ApiResponse<UtcTimeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Emby-Authorization"] = this.configuration.apiKey("X-Emby-Authorization"); // CustomAuthentication authentication
        }

        const response = await this.request({
            path: `/GetUtcTime`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UtcTimeResponseFromJSON(jsonValue));
    }

    /**
     * Gets the current utc time.
     */
    async getUtcTime(): Promise<UtcTimeResponse> {
        const response = await this.getUtcTimeRaw();
        return await response.value();
    }

}
