/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityLogEntry,
    ActivityLogEntryFromJSON,
    ActivityLogEntryFromJSONTyped,
    ActivityLogEntryToJSON,
} from './';

/**
 * 
 * @export
 * @interface ActivityLogEntryQueryResult
 */
export interface ActivityLogEntryQueryResult {
    /**
     * Gets or sets the items.
     * @type {Array<ActivityLogEntry>}
     * @memberof ActivityLogEntryQueryResult
     */
    items?: Array<ActivityLogEntry> | null;
    /**
     * The total number of records available.
     * @type {number}
     * @memberof ActivityLogEntryQueryResult
     */
    totalRecordCount?: number;
    /**
     * The index of the first record in Items.
     * @type {number}
     * @memberof ActivityLogEntryQueryResult
     */
    startIndex?: number;
}

export function ActivityLogEntryQueryResultFromJSON(json: any): ActivityLogEntryQueryResult {
    return ActivityLogEntryQueryResultFromJSONTyped(json, false);
}

export function ActivityLogEntryQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogEntryQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'Items') ? undefined : (json['Items'] === null ? null : (json['Items'] as Array<any>).map(ActivityLogEntryFromJSON)),
        'totalRecordCount': !exists(json, 'TotalRecordCount') ? undefined : json['TotalRecordCount'],
        'startIndex': !exists(json, 'StartIndex') ? undefined : json['StartIndex'],
    };
}

export function ActivityLogEntryQueryResultToJSON(value?: ActivityLogEntryQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(ActivityLogEntryToJSON)),
        'TotalRecordCount': value.totalRecordCount,
        'StartIndex': value.startIndex,
    };
}


