/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CodecType,
    CodecTypeFromJSON,
    CodecTypeFromJSONTyped,
    CodecTypeToJSON,
    ProfileCondition,
    ProfileConditionFromJSON,
    ProfileConditionFromJSONTyped,
    ProfileConditionToJSON,
} from './';

/**
 * 
 * @export
 * @interface CodecProfile
 */
export interface CodecProfile {
    /**
     * 
     * @type {CodecType}
     * @memberof CodecProfile
     */
    type?: CodecType;
    /**
     * 
     * @type {Array<ProfileCondition>}
     * @memberof CodecProfile
     */
    conditions?: Array<ProfileCondition> | null;
    /**
     * 
     * @type {Array<ProfileCondition>}
     * @memberof CodecProfile
     */
    applyConditions?: Array<ProfileCondition> | null;
    /**
     * 
     * @type {string}
     * @memberof CodecProfile
     */
    codec?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CodecProfile
     */
    container?: string | null;
}

export function CodecProfileFromJSON(json: any): CodecProfile {
    return CodecProfileFromJSONTyped(json, false);
}

export function CodecProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodecProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'Type') ? undefined : CodecTypeFromJSON(json['Type']),
        'conditions': !exists(json, 'Conditions') ? undefined : (json['Conditions'] === null ? null : (json['Conditions'] as Array<any>).map(ProfileConditionFromJSON)),
        'applyConditions': !exists(json, 'ApplyConditions') ? undefined : (json['ApplyConditions'] === null ? null : (json['ApplyConditions'] as Array<any>).map(ProfileConditionFromJSON)),
        'codec': !exists(json, 'Codec') ? undefined : json['Codec'],
        'container': !exists(json, 'Container') ? undefined : json['Container'],
    };
}

export function CodecProfileToJSON(value?: CodecProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Type': CodecTypeToJSON(value.type),
        'Conditions': value.conditions === undefined ? undefined : (value.conditions === null ? null : (value.conditions as Array<any>).map(ProfileConditionToJSON)),
        'ApplyConditions': value.applyConditions === undefined ? undefined : (value.applyConditions === null ? null : (value.applyConditions as Array<any>).map(ProfileConditionToJSON)),
        'Codec': value.codec,
        'Container': value.container,
    };
}


