/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControlResponse
 */
export interface ControlResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ControlResponse
     */
    readonly headers?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof ControlResponse
     */
    xml?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ControlResponse
     */
    isSuccessful?: boolean;
}

export function ControlResponseFromJSON(json: any): ControlResponse {
    return ControlResponseFromJSONTyped(json, false);
}

export function ControlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'headers': !exists(json, 'Headers') ? undefined : json['Headers'],
        'xml': !exists(json, 'Xml') ? undefined : json['Xml'],
        'isSuccessful': !exists(json, 'IsSuccessful') ? undefined : json['IsSuccessful'],
    };
}

export function ControlResponseToJSON(value?: ControlResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Xml': value.xml,
        'IsSuccessful': value.isSuccessful,
    };
}


