/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Class CountryInfo.
 * @export
 * @interface CountryInfo
 */
export interface CountryInfo {
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof CountryInfo
     */
    name?: string | null;
    /**
     * Gets or sets the display name.
     * @type {string}
     * @memberof CountryInfo
     */
    displayName?: string | null;
    /**
     * Gets or sets the name of the two letter ISO region.
     * @type {string}
     * @memberof CountryInfo
     */
    twoLetterISORegionName?: string | null;
    /**
     * Gets or sets the name of the three letter ISO region.
     * @type {string}
     * @memberof CountryInfo
     */
    threeLetterISORegionName?: string | null;
}

export function CountryInfoFromJSON(json: any): CountryInfo {
    return CountryInfoFromJSONTyped(json, false);
}

export function CountryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'displayName': !exists(json, 'DisplayName') ? undefined : json['DisplayName'],
        'twoLetterISORegionName': !exists(json, 'TwoLetterISORegionName') ? undefined : json['TwoLetterISORegionName'],
        'threeLetterISORegionName': !exists(json, 'ThreeLetterISORegionName') ? undefined : json['ThreeLetterISORegionName'],
    };
}

export function CountryInfoToJSON(value?: CountryInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'DisplayName': value.displayName,
        'TwoLetterISORegionName': value.twoLetterISORegionName,
        'ThreeLetterISORegionName': value.threeLetterISORegionName,
    };
}


