/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeviceProfileType,
    DeviceProfileTypeFromJSON,
    DeviceProfileTypeFromJSONTyped,
    DeviceProfileTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeviceProfileInfo
 */
export interface DeviceProfileInfo {
    /**
     * Gets or sets the identifier.
     * @type {string}
     * @memberof DeviceProfileInfo
     */
    id?: string | null;
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof DeviceProfileInfo
     */
    name?: string | null;
    /**
     * 
     * @type {DeviceProfileType}
     * @memberof DeviceProfileInfo
     */
    type?: DeviceProfileType;
}

export function DeviceProfileInfoFromJSON(json: any): DeviceProfileInfo {
    return DeviceProfileInfoFromJSONTyped(json, false);
}

export function DeviceProfileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceProfileInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'type': !exists(json, 'Type') ? undefined : DeviceProfileTypeFromJSON(json['Type']),
    };
}

export function DeviceProfileInfoToJSON(value?: DeviceProfileInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'Type': DeviceProfileTypeToJSON(value.type),
    };
}


