/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceOptions
 */
export interface DeviceOptions {
    /**
     * 
     * @type {string}
     * @memberof DeviceOptions
     */
    customName?: string | null;
}

export function DeviceOptionsFromJSON(json: any): DeviceOptions {
    return DeviceOptionsFromJSONTyped(json, false);
}

export function DeviceOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customName': !exists(json, 'CustomName') ? undefined : json['CustomName'],
    };
}

export function DeviceOptionsToJSON(value?: DeviceOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CustomName': value.customName,
    };
}


