/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuideInfo
 */
export interface GuideInfo {
    /**
     * Gets or sets the start date.
     * @type {Date}
     * @memberof GuideInfo
     */
    startDate?: Date;
    /**
     * Gets or sets the end date.
     * @type {Date}
     * @memberof GuideInfo
     */
    endDate?: Date;
}

export function GuideInfoFromJSON(json: any): GuideInfo {
    return GuideInfoFromJSONTyped(json, false);
}

export function GuideInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuideInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startDate': !exists(json, 'StartDate') ? undefined : (new Date(json['StartDate'])),
        'endDate': !exists(json, 'EndDate') ? undefined : (new Date(json['EndDate'])),
    };
}

export function GuideInfoToJSON(value?: GuideInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'StartDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'EndDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
    };
}


