/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ImageOrientation {
    TopLeft = 'TopLeft',
    TopRight = 'TopRight',
    BottomRight = 'BottomRight',
    BottomLeft = 'BottomLeft',
    LeftTop = 'LeftTop',
    RightTop = 'RightTop',
    RightBottom = 'RightBottom',
    LeftBottom = 'LeftBottom'
}

export function ImageOrientationFromJSON(json: any): ImageOrientation {
    return ImageOrientationFromJSONTyped(json, false);
}

export function ImageOrientationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageOrientation {
    return json as ImageOrientation;
}

export function ImageOrientationToJSON(value?: ImageOrientation | null): any {
    return value as any;
}

