/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ImageSavingConvention {
    Legacy = 'Legacy',
    Compatible = 'Compatible'
}

export function ImageSavingConventionFromJSON(json: any): ImageSavingConvention {
    return ImageSavingConventionFromJSONTyped(json, false);
}

export function ImageSavingConventionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageSavingConvention {
    return json as ImageSavingConvention;
}

export function ImageSavingConventionToJSON(value?: ImageSavingConvention | null): any {
    return value as any;
}

