/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Enum IsoType.
 * @export
 * @enum {string}
 */
export enum IsoType {
    Dvd = 'Dvd',
    BluRay = 'BluRay'
}

export function IsoTypeFromJSON(json: any): IsoType {
    return IsoTypeFromJSONTyped(json, false);
}

export function IsoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsoType {
    return json as IsoType;
}

export function IsoTypeToJSON(value?: IsoType | null): any {
    return value as any;
}

