/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Enum ItemFilter.
 * @export
 * @enum {string}
 */
export enum ItemFilter {
    IsFolder = 'IsFolder',
    IsNotFolder = 'IsNotFolder',
    IsUnplayed = 'IsUnplayed',
    IsPlayed = 'IsPlayed',
    IsFavorite = 'IsFavorite',
    IsResumable = 'IsResumable',
    Likes = 'Likes',
    Dislikes = 'Dislikes',
    IsFavoriteOrLikes = 'IsFavoriteOrLikes'
}

export function ItemFilterFromJSON(json: any): ItemFilter {
    return ItemFilterFromJSONTyped(json, false);
}

export function ItemFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemFilter {
    return json as ItemFilter;
}

export function ItemFilterToJSON(value?: ItemFilter | null): any {
    return value as any;
}

