/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Library option info dto.
 * @export
 * @interface LibraryOptionInfoDto
 */
export interface LibraryOptionInfoDto {
    /**
     * Gets or sets name.
     * @type {string}
     * @memberof LibraryOptionInfoDto
     */
    name?: string | null;
    /**
     * Gets or sets a value indicating whether default enabled.
     * @type {boolean}
     * @memberof LibraryOptionInfoDto
     */
    defaultEnabled?: boolean;
}

export function LibraryOptionInfoDtoFromJSON(json: any): LibraryOptionInfoDto {
    return LibraryOptionInfoDtoFromJSONTyped(json, false);
}

export function LibraryOptionInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibraryOptionInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'defaultEnabled': !exists(json, 'DefaultEnabled') ? undefined : json['DefaultEnabled'],
    };
}

export function LibraryOptionInfoDtoToJSON(value?: LibraryOptionInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'DefaultEnabled': value.defaultEnabled,
    };
}


