/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LiveTvServiceInfo,
    LiveTvServiceInfoFromJSON,
    LiveTvServiceInfoFromJSONTyped,
    LiveTvServiceInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface LiveTvInfo
 */
export interface LiveTvInfo {
    /**
     * Gets or sets the services.
     * @type {Array<LiveTvServiceInfo>}
     * @memberof LiveTvInfo
     */
    services?: Array<LiveTvServiceInfo> | null;
    /**
     * Gets or sets a value indicating whether this instance is enabled.
     * @type {boolean}
     * @memberof LiveTvInfo
     */
    isEnabled?: boolean;
    /**
     * Gets or sets the enabled users.
     * @type {Array<string>}
     * @memberof LiveTvInfo
     */
    enabledUsers?: Array<string> | null;
}

export function LiveTvInfoFromJSON(json: any): LiveTvInfo {
    return LiveTvInfoFromJSONTyped(json, false);
}

export function LiveTvInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveTvInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'services': !exists(json, 'Services') ? undefined : (json['Services'] === null ? null : (json['Services'] as Array<any>).map(LiveTvServiceInfoFromJSON)),
        'isEnabled': !exists(json, 'IsEnabled') ? undefined : json['IsEnabled'],
        'enabledUsers': !exists(json, 'EnabledUsers') ? undefined : json['EnabledUsers'],
    };
}

export function LiveTvInfoToJSON(value?: LiveTvInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Services': value.services === undefined ? undefined : (value.services === null ? null : (value.services as Array<any>).map(LiveTvServiceInfoToJSON)),
        'IsEnabled': value.isEnabled,
        'EnabledUsers': value.enabledUsers,
    };
}


