/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MediaSourceInfo,
    MediaSourceInfoFromJSON,
    MediaSourceInfoFromJSONTyped,
    MediaSourceInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface LiveStreamResponse
 */
export interface LiveStreamResponse {
    /**
     * 
     * @type {MediaSourceInfo}
     * @memberof LiveStreamResponse
     */
    mediaSource?: MediaSourceInfo;
}

export function LiveStreamResponseFromJSON(json: any): LiveStreamResponse {
    return LiveStreamResponseFromJSONTyped(json, false);
}

export function LiveStreamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveStreamResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mediaSource': !exists(json, 'MediaSource') ? undefined : MediaSourceInfoFromJSON(json['MediaSource']),
    };
}

export function LiveStreamResponseToJSON(value?: LiveStreamResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'MediaSource': MediaSourceInfoToJSON(value.mediaSource),
    };
}


