/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogFile
 */
export interface LogFile {
    /**
     * Gets or sets the date created.
     * @type {Date}
     * @memberof LogFile
     */
    dateCreated?: Date;
    /**
     * Gets or sets the date modified.
     * @type {Date}
     * @memberof LogFile
     */
    dateModified?: Date;
    /**
     * Gets or sets the size.
     * @type {number}
     * @memberof LogFile
     */
    size?: number;
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof LogFile
     */
    name?: string | null;
}

export function LogFileFromJSON(json: any): LogFile {
    return LogFileFromJSONTyped(json, false);
}

export function LogFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateCreated': !exists(json, 'DateCreated') ? undefined : (new Date(json['DateCreated'])),
        'dateModified': !exists(json, 'DateModified') ? undefined : (new Date(json['DateModified'])),
        'size': !exists(json, 'Size') ? undefined : json['Size'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function LogFileToJSON(value?: LogFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DateCreated': value.dateCreated === undefined ? undefined : (value.dateCreated.toISOString()),
        'DateModified': value.dateModified === undefined ? undefined : (value.dateModified.toISOString()),
        'Size': value.size,
        'Name': value.name,
    };
}


