/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MusicVideoInfo,
    MusicVideoInfoFromJSON,
    MusicVideoInfoFromJSONTyped,
    MusicVideoInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface MusicVideoInfoRemoteSearchQuery
 */
export interface MusicVideoInfoRemoteSearchQuery {
    /**
     * 
     * @type {MusicVideoInfo}
     * @memberof MusicVideoInfoRemoteSearchQuery
     */
    searchInfo?: MusicVideoInfo;
    /**
     * 
     * @type {string}
     * @memberof MusicVideoInfoRemoteSearchQuery
     */
    itemId?: string;
    /**
     * Will only search within the given provider when set.
     * @type {string}
     * @memberof MusicVideoInfoRemoteSearchQuery
     */
    searchProviderName?: string | null;
    /**
     * Gets or sets a value indicating whether disabled providers should be included.
     * @type {boolean}
     * @memberof MusicVideoInfoRemoteSearchQuery
     */
    includeDisabledProviders?: boolean;
}

export function MusicVideoInfoRemoteSearchQueryFromJSON(json: any): MusicVideoInfoRemoteSearchQuery {
    return MusicVideoInfoRemoteSearchQueryFromJSONTyped(json, false);
}

export function MusicVideoInfoRemoteSearchQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicVideoInfoRemoteSearchQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchInfo': !exists(json, 'SearchInfo') ? undefined : MusicVideoInfoFromJSON(json['SearchInfo']),
        'itemId': !exists(json, 'ItemId') ? undefined : json['ItemId'],
        'searchProviderName': !exists(json, 'SearchProviderName') ? undefined : json['SearchProviderName'],
        'includeDisabledProviders': !exists(json, 'IncludeDisabledProviders') ? undefined : json['IncludeDisabledProviders'],
    };
}

export function MusicVideoInfoRemoteSearchQueryToJSON(value?: MusicVideoInfoRemoteSearchQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SearchInfo': MusicVideoInfoToJSON(value.searchInfo),
        'ItemId': value.itemId,
        'SearchProviderName': value.searchProviderName,
        'IncludeDisabledProviders': value.includeDisabledProviders,
    };
}


