/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NotificationDto,
    NotificationDtoFromJSON,
    NotificationDtoFromJSONTyped,
    NotificationDtoToJSON,
} from './';

/**
 * A list of notifications with the total record count for pagination.
 * @export
 * @interface NotificationResultDto
 */
export interface NotificationResultDto {
    /**
     * Gets or sets the current page of notifications.
     * @type {Array<NotificationDto>}
     * @memberof NotificationResultDto
     */
    notifications?: Array<NotificationDto> | null;
    /**
     * Gets or sets the total number of notifications.
     * @type {number}
     * @memberof NotificationResultDto
     */
    totalRecordCount?: number;
}

export function NotificationResultDtoFromJSON(json: any): NotificationResultDto {
    return NotificationResultDtoFromJSONTyped(json, false);
}

export function NotificationResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notifications': !exists(json, 'Notifications') ? undefined : (json['Notifications'] === null ? null : (json['Notifications'] as Array<any>).map(NotificationDtoFromJSON)),
        'totalRecordCount': !exists(json, 'TotalRecordCount') ? undefined : json['TotalRecordCount'],
    };
}

export function NotificationResultDtoToJSON(value?: NotificationResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Notifications': value.notifications === undefined ? undefined : (value.notifications === null ? null : (value.notifications as Array<any>).map(NotificationDtoToJSON)),
        'TotalRecordCount': value.totalRecordCount,
    };
}


