/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Plugin security info.
 * @export
 * @interface PluginSecurityInfo
 */
export interface PluginSecurityInfo {
    /**
     * Gets or sets the supporter key.
     * @type {string}
     * @memberof PluginSecurityInfo
     */
    supporterKey?: string | null;
    /**
     * Gets or sets a value indicating whether is mb supporter.
     * @type {boolean}
     * @memberof PluginSecurityInfo
     */
    isMbSupporter?: boolean;
}

export function PluginSecurityInfoFromJSON(json: any): PluginSecurityInfo {
    return PluginSecurityInfoFromJSONTyped(json, false);
}

export function PluginSecurityInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginSecurityInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'supporterKey': !exists(json, 'SupporterKey') ? undefined : json['SupporterKey'],
        'isMbSupporter': !exists(json, 'IsMbSupporter') ? undefined : json['IsMbSupporter'],
    };
}

export function PluginSecurityInfoToJSON(value?: PluginSecurityInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SupporterKey': value.supporterKey,
        'IsMbSupporter': value.isMbSupporter,
    };
}


