/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryFiltersLegacy
 */
export interface QueryFiltersLegacy {
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryFiltersLegacy
     */
    genres?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryFiltersLegacy
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryFiltersLegacy
     */
    officialRatings?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof QueryFiltersLegacy
     */
    years?: Array<number> | null;
}

export function QueryFiltersLegacyFromJSON(json: any): QueryFiltersLegacy {
    return QueryFiltersLegacyFromJSONTyped(json, false);
}

export function QueryFiltersLegacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryFiltersLegacy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'genres': !exists(json, 'Genres') ? undefined : json['Genres'],
        'tags': !exists(json, 'Tags') ? undefined : json['Tags'],
        'officialRatings': !exists(json, 'OfficialRatings') ? undefined : json['OfficialRatings'],
        'years': !exists(json, 'Years') ? undefined : json['Years'],
    };
}

export function QueryFiltersLegacyToJSON(value?: QueryFiltersLegacy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Genres': value.genres,
        'Tags': value.tags,
        'OfficialRatings': value.officialRatings,
        'Years': value.years,
    };
}


