/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RecordingStatus {
    New = 'New',
    InProgress = 'InProgress',
    Completed = 'Completed',
    Cancelled = 'Cancelled',
    ConflictedOk = 'ConflictedOk',
    ConflictedNotOk = 'ConflictedNotOk',
    Error = 'Error'
}

export function RecordingStatusFromJSON(json: any): RecordingStatus {
    return RecordingStatusFromJSONTyped(json, false);
}

export function RecordingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordingStatus {
    return json as RecordingStatus;
}

export function RecordingStatusToJSON(value?: RecordingStatus | null): any {
    return value as any;
}

