/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteSearchResult
 */
export interface RemoteSearchResult {
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof RemoteSearchResult
     */
    name?: string | null;
    /**
     * Gets or sets the provider ids.
     * @type {{ [key: string]: string; }}
     * @memberof RemoteSearchResult
     */
    providerIds?: { [key: string]: string; } | null;
    /**
     * Gets or sets the year.
     * @type {number}
     * @memberof RemoteSearchResult
     */
    productionYear?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RemoteSearchResult
     */
    indexNumber?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RemoteSearchResult
     */
    indexNumberEnd?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RemoteSearchResult
     */
    parentIndexNumber?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof RemoteSearchResult
     */
    premiereDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RemoteSearchResult
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RemoteSearchResult
     */
    searchProviderName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RemoteSearchResult
     */
    overview?: string | null;
    /**
     * 
     * @type {RemoteSearchResult}
     * @memberof RemoteSearchResult
     */
    albumArtist?: RemoteSearchResult;
    /**
     * 
     * @type {Array<RemoteSearchResult>}
     * @memberof RemoteSearchResult
     */
    artists?: Array<RemoteSearchResult> | null;
}

export function RemoteSearchResultFromJSON(json: any): RemoteSearchResult {
    return RemoteSearchResultFromJSONTyped(json, false);
}

export function RemoteSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteSearchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'providerIds': !exists(json, 'ProviderIds') ? undefined : json['ProviderIds'],
        'productionYear': !exists(json, 'ProductionYear') ? undefined : json['ProductionYear'],
        'indexNumber': !exists(json, 'IndexNumber') ? undefined : json['IndexNumber'],
        'indexNumberEnd': !exists(json, 'IndexNumberEnd') ? undefined : json['IndexNumberEnd'],
        'parentIndexNumber': !exists(json, 'ParentIndexNumber') ? undefined : json['ParentIndexNumber'],
        'premiereDate': !exists(json, 'PremiereDate') ? undefined : (json['PremiereDate'] === null ? null : new Date(json['PremiereDate'])),
        'imageUrl': !exists(json, 'ImageUrl') ? undefined : json['ImageUrl'],
        'searchProviderName': !exists(json, 'SearchProviderName') ? undefined : json['SearchProviderName'],
        'overview': !exists(json, 'Overview') ? undefined : json['Overview'],
        'albumArtist': !exists(json, 'AlbumArtist') ? undefined : RemoteSearchResultFromJSON(json['AlbumArtist']),
        'artists': !exists(json, 'Artists') ? undefined : (json['Artists'] === null ? null : (json['Artists'] as Array<any>).map(RemoteSearchResultFromJSON)),
    };
}

export function RemoteSearchResultToJSON(value?: RemoteSearchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'ProviderIds': value.providerIds,
        'ProductionYear': value.productionYear,
        'IndexNumber': value.indexNumber,
        'IndexNumberEnd': value.indexNumberEnd,
        'ParentIndexNumber': value.parentIndexNumber,
        'PremiereDate': value.premiereDate === undefined ? undefined : (value.premiereDate === null ? null : value.premiereDate.toISOString()),
        'ImageUrl': value.imageUrl,
        'SearchProviderName': value.searchProviderName,
        'Overview': value.overview,
        'AlbumArtist': RemoteSearchResultToJSON(value.albumArtist),
        'Artists': value.artists === undefined ? undefined : (value.artists === null ? null : (value.artists as Array<any>).map(RemoteSearchResultToJSON)),
    };
}


