/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Class RepositoryInfo.
 * @export
 * @interface RepositoryInfo
 */
export interface RepositoryInfo {
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof RepositoryInfo
     */
    name?: string | null;
    /**
     * Gets or sets the URL.
     * @type {string}
     * @memberof RepositoryInfo
     */
    url?: string | null;
}

export function RepositoryInfoFromJSON(json: any): RepositoryInfo {
    return RepositoryInfoFromJSONTyped(json, false);
}

export function RepositoryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepositoryInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'url': !exists(json, 'Url') ? undefined : json['Url'],
    };
}

export function RepositoryInfoToJSON(value?: RepositoryInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Url': value.url,
    };
}


