/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SearchHint,
    SearchHintFromJSON,
    SearchHintFromJSONTyped,
    SearchHintToJSON,
} from './';

/**
 * Class SearchHintResult.
 * @export
 * @interface SearchHintResult
 */
export interface SearchHintResult {
    /**
     * Gets or sets the search hints.
     * @type {Array<SearchHint>}
     * @memberof SearchHintResult
     */
    searchHints?: Array<SearchHint> | null;
    /**
     * Gets or sets the total record count.
     * @type {number}
     * @memberof SearchHintResult
     */
    totalRecordCount?: number;
}

export function SearchHintResultFromJSON(json: any): SearchHintResult {
    return SearchHintResultFromJSONTyped(json, false);
}

export function SearchHintResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchHintResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchHints': !exists(json, 'SearchHints') ? undefined : (json['SearchHints'] === null ? null : (json['SearchHints'] as Array<any>).map(SearchHintFromJSON)),
        'totalRecordCount': !exists(json, 'TotalRecordCount') ? undefined : json['TotalRecordCount'],
    };
}

export function SearchHintResultToJSON(value?: SearchHintResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SearchHints': value.searchHints === undefined ? undefined : (value.searchHints === null ? null : (value.searchHints as Array<any>).map(SearchHintToJSON)),
        'TotalRecordCount': value.totalRecordCount,
    };
}


