/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SeriesInfo,
    SeriesInfoFromJSON,
    SeriesInfoFromJSONTyped,
    SeriesInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface SeriesInfoRemoteSearchQuery
 */
export interface SeriesInfoRemoteSearchQuery {
    /**
     * 
     * @type {SeriesInfo}
     * @memberof SeriesInfoRemoteSearchQuery
     */
    searchInfo?: SeriesInfo;
    /**
     * 
     * @type {string}
     * @memberof SeriesInfoRemoteSearchQuery
     */
    itemId?: string;
    /**
     * Will only search within the given provider when set.
     * @type {string}
     * @memberof SeriesInfoRemoteSearchQuery
     */
    searchProviderName?: string | null;
    /**
     * Gets or sets a value indicating whether disabled providers should be included.
     * @type {boolean}
     * @memberof SeriesInfoRemoteSearchQuery
     */
    includeDisabledProviders?: boolean;
}

export function SeriesInfoRemoteSearchQueryFromJSON(json: any): SeriesInfoRemoteSearchQuery {
    return SeriesInfoRemoteSearchQueryFromJSONTyped(json, false);
}

export function SeriesInfoRemoteSearchQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesInfoRemoteSearchQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchInfo': !exists(json, 'SearchInfo') ? undefined : SeriesInfoFromJSON(json['SearchInfo']),
        'itemId': !exists(json, 'ItemId') ? undefined : json['ItemId'],
        'searchProviderName': !exists(json, 'SearchProviderName') ? undefined : json['SearchProviderName'],
        'includeDisabledProviders': !exists(json, 'IncludeDisabledProviders') ? undefined : json['IncludeDisabledProviders'],
    };
}

export function SeriesInfoRemoteSearchQueryToJSON(value?: SeriesInfoRemoteSearchQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SearchInfo': SeriesInfoToJSON(value.searchInfo),
        'ItemId': value.itemId,
        'SearchProviderName': value.searchProviderName,
        'IncludeDisabledProviders': value.includeDisabledProviders,
    };
}


