/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Startup remote access dto.
 * @export
 * @interface StartupRemoteAccessDto
 */
export interface StartupRemoteAccessDto {
    /**
     * Gets or sets a value indicating whether enable remote access.
     * @type {boolean}
     * @memberof StartupRemoteAccessDto
     */
    enableRemoteAccess: boolean;
    /**
     * Gets or sets a value indicating whether enable automatic port mapping.
     * @type {boolean}
     * @memberof StartupRemoteAccessDto
     */
    enableAutomaticPortMapping: boolean;
}

export function StartupRemoteAccessDtoFromJSON(json: any): StartupRemoteAccessDto {
    return StartupRemoteAccessDtoFromJSONTyped(json, false);
}

export function StartupRemoteAccessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartupRemoteAccessDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enableRemoteAccess': json['EnableRemoteAccess'],
        'enableAutomaticPortMapping': json['EnableAutomaticPortMapping'],
    };
}

export function StartupRemoteAccessDtoToJSON(value?: StartupRemoteAccessDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EnableRemoteAccess': value.enableRemoteAccess,
        'EnableAutomaticPortMapping': value.enableAutomaticPortMapping,
    };
}


