/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Enum TaskState.
 * @export
 * @enum {string}
 */
export enum TaskState {
    Idle = 'Idle',
    Cancelling = 'Cancelling',
    Running = 'Running'
}

export function TaskStateFromJSON(json: any): TaskState {
    return TaskStateFromJSONTyped(json, false);
}

export function TaskStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskState {
    return json as TaskState;
}

export function TaskStateToJSON(value?: TaskState | null): any {
    return value as any;
}

