/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TrailerInfo,
    TrailerInfoFromJSON,
    TrailerInfoFromJSONTyped,
    TrailerInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface TrailerInfoRemoteSearchQuery
 */
export interface TrailerInfoRemoteSearchQuery {
    /**
     * 
     * @type {TrailerInfo}
     * @memberof TrailerInfoRemoteSearchQuery
     */
    searchInfo?: TrailerInfo;
    /**
     * 
     * @type {string}
     * @memberof TrailerInfoRemoteSearchQuery
     */
    itemId?: string;
    /**
     * Will only search within the given provider when set.
     * @type {string}
     * @memberof TrailerInfoRemoteSearchQuery
     */
    searchProviderName?: string | null;
    /**
     * Gets or sets a value indicating whether disabled providers should be included.
     * @type {boolean}
     * @memberof TrailerInfoRemoteSearchQuery
     */
    includeDisabledProviders?: boolean;
}

export function TrailerInfoRemoteSearchQueryFromJSON(json: any): TrailerInfoRemoteSearchQuery {
    return TrailerInfoRemoteSearchQueryFromJSONTyped(json, false);
}

export function TrailerInfoRemoteSearchQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrailerInfoRemoteSearchQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchInfo': !exists(json, 'SearchInfo') ? undefined : TrailerInfoFromJSON(json['SearchInfo']),
        'itemId': !exists(json, 'ItemId') ? undefined : json['ItemId'],
        'searchProviderName': !exists(json, 'SearchProviderName') ? undefined : json['SearchProviderName'],
        'includeDisabledProviders': !exists(json, 'IncludeDisabledProviders') ? undefined : json['IncludeDisabledProviders'],
    };
}

export function TrailerInfoRemoteSearchQueryToJSON(value?: TrailerInfoRemoteSearchQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SearchInfo': TrailerInfoToJSON(value.searchInfo),
        'ItemId': value.itemId,
        'SearchProviderName': value.searchProviderName,
        'IncludeDisabledProviders': value.includeDisabledProviders,
    };
}


