/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TunerHostInfo
 */
export interface TunerHostInfo {
    /**
     * 
     * @type {string}
     * @memberof TunerHostInfo
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TunerHostInfo
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TunerHostInfo
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TunerHostInfo
     */
    deviceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TunerHostInfo
     */
    friendlyName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TunerHostInfo
     */
    importFavoritesOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TunerHostInfo
     */
    allowHWTranscoding?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TunerHostInfo
     */
    enableStreamLooping?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TunerHostInfo
     */
    source?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TunerHostInfo
     */
    tunerCount?: number;
    /**
     * 
     * @type {string}
     * @memberof TunerHostInfo
     */
    userAgent?: string | null;
}

export function TunerHostInfoFromJSON(json: any): TunerHostInfo {
    return TunerHostInfoFromJSONTyped(json, false);
}

export function TunerHostInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TunerHostInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'url': !exists(json, 'Url') ? undefined : json['Url'],
        'type': !exists(json, 'Type') ? undefined : json['Type'],
        'deviceId': !exists(json, 'DeviceId') ? undefined : json['DeviceId'],
        'friendlyName': !exists(json, 'FriendlyName') ? undefined : json['FriendlyName'],
        'importFavoritesOnly': !exists(json, 'ImportFavoritesOnly') ? undefined : json['ImportFavoritesOnly'],
        'allowHWTranscoding': !exists(json, 'AllowHWTranscoding') ? undefined : json['AllowHWTranscoding'],
        'enableStreamLooping': !exists(json, 'EnableStreamLooping') ? undefined : json['EnableStreamLooping'],
        'source': !exists(json, 'Source') ? undefined : json['Source'],
        'tunerCount': !exists(json, 'TunerCount') ? undefined : json['TunerCount'],
        'userAgent': !exists(json, 'UserAgent') ? undefined : json['UserAgent'],
    };
}

export function TunerHostInfoToJSON(value?: TunerHostInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Url': value.url,
        'Type': value.type,
        'DeviceId': value.deviceId,
        'FriendlyName': value.friendlyName,
        'ImportFavoritesOnly': value.importFavoritesOnly,
        'AllowHWTranscoding': value.allowHWTranscoding,
        'EnableStreamLooping': value.enableStreamLooping,
        'Source': value.source,
        'TunerCount': value.tunerCount,
        'UserAgent': value.userAgent,
    };
}


