/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The update user easy password request body.
 * @export
 * @interface UpdateUserEasyPassword
 */
export interface UpdateUserEasyPassword {
    /**
     * Gets or sets the new sha1-hashed password.
     * @type {string}
     * @memberof UpdateUserEasyPassword
     */
    newPassword?: string | null;
    /**
     * Gets or sets the new password.
     * @type {string}
     * @memberof UpdateUserEasyPassword
     */
    newPw?: string | null;
    /**
     * Gets or sets a value indicating whether to reset the password.
     * @type {boolean}
     * @memberof UpdateUserEasyPassword
     */
    resetPassword?: boolean;
}

export function UpdateUserEasyPasswordFromJSON(json: any): UpdateUserEasyPassword {
    return UpdateUserEasyPasswordFromJSONTyped(json, false);
}

export function UpdateUserEasyPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserEasyPassword {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newPassword': !exists(json, 'NewPassword') ? undefined : json['NewPassword'],
        'newPw': !exists(json, 'NewPw') ? undefined : json['NewPw'],
        'resetPassword': !exists(json, 'ResetPassword') ? undefined : json['ResetPassword'],
    };
}

export function UpdateUserEasyPasswordToJSON(value?: UpdateUserEasyPassword | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NewPassword': value.newPassword,
        'NewPw': value.newPw,
        'ResetPassword': value.resetPassword,
    };
}


