/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Upload subtitles dto.
 * @export
 * @interface UploadSubtitleDto
 */
export interface UploadSubtitleDto {
    /**
     * Gets or sets the subtitle language.
     * @type {string}
     * @memberof UploadSubtitleDto
     */
    language: string;
    /**
     * Gets or sets the subtitle format.
     * @type {string}
     * @memberof UploadSubtitleDto
     */
    format: string;
    /**
     * Gets or sets a value indicating whether the subtitle is forced.
     * @type {boolean}
     * @memberof UploadSubtitleDto
     */
    isForced: boolean;
    /**
     * Gets or sets the subtitle data.
     * @type {string}
     * @memberof UploadSubtitleDto
     */
    data: string;
}

export function UploadSubtitleDtoFromJSON(json: any): UploadSubtitleDto {
    return UploadSubtitleDtoFromJSONTyped(json, false);
}

export function UploadSubtitleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSubtitleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'language': json['Language'],
        'format': json['Format'],
        'isForced': json['IsForced'],
        'data': json['Data'],
    };
}

export function UploadSubtitleDtoToJSON(value?: UploadSubtitleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Language': value.language,
        'Format': value.format,
        'IsForced': value.isForced,
        'Data': value.data,
    };
}


