/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Validate path object.
 * @export
 * @interface ValidatePathDto
 */
export interface ValidatePathDto {
    /**
     * Gets or sets a value indicating whether validate if path is writable.
     * @type {boolean}
     * @memberof ValidatePathDto
     */
    validateWritable?: boolean;
    /**
     * Gets or sets the path.
     * @type {string}
     * @memberof ValidatePathDto
     */
    path?: string | null;
    /**
     * Gets or sets is path file.
     * @type {boolean}
     * @memberof ValidatePathDto
     */
    isFile?: boolean | null;
}

export function ValidatePathDtoFromJSON(json: any): ValidatePathDto {
    return ValidatePathDtoFromJSONTyped(json, false);
}

export function ValidatePathDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatePathDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validateWritable': !exists(json, 'ValidateWritable') ? undefined : json['ValidateWritable'],
        'path': !exists(json, 'Path') ? undefined : json['Path'],
        'isFile': !exists(json, 'IsFile') ? undefined : json['IsFile'],
    };
}

export function ValidatePathDtoToJSON(value?: ValidatePathDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ValidateWritable': value.validateWritable,
        'Path': value.path,
        'IsFile': value.isFile,
    };
}


