/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Version
 */
export interface Version {
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    readonly major?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    readonly minor?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    readonly build?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    readonly revision?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    readonly majorRevision?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    readonly minorRevision?: number;
}

export function VersionFromJSON(json: any): Version {
    return VersionFromJSONTyped(json, false);
}

export function VersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Version {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'major': !exists(json, 'Major') ? undefined : json['Major'],
        'minor': !exists(json, 'Minor') ? undefined : json['Minor'],
        'build': !exists(json, 'Build') ? undefined : json['Build'],
        'revision': !exists(json, 'Revision') ? undefined : json['Revision'],
        'majorRevision': !exists(json, 'MajorRevision') ? undefined : json['MajorRevision'],
        'minorRevision': !exists(json, 'MinorRevision') ? undefined : json['MinorRevision'],
    };
}

export function VersionToJSON(value?: Version | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


